### PR TITLE
fixes: develop docker will never create new build

### PR DESCRIPTION
**Pull request by smellman**
Changes proposed in this pull request:
- fixes: Dockerfile for develop branch will never create new build because nothing changed
  - update.sh check current branch's hash and fetch only this hash

@pgRouting/admins

### CODE REVIEW

**Comment by smellman** [comment]
Note: I added : before hash in git fetch to support old git command.

```
git fetch --depth 1 origin :d93c618ae9c2c57885c8a52287ae226ee7b9a4a4
```

**Comment by aruneko** [comment]
I have a question for @cvvergara .

Which branch is for developing? It seems that master branch is ahead of develop branch.

**Comment by smellman** [comment]
It is easy to supports both develop and master branch.

**Comment by dkastl** [comment]
@aruneko , you're right. We should probably follow the same convention as in other repositories to first point PR's in `develop` branch and merge from there into `master`. But we also lack somehow releases and versioning for this repository.

**Comment by smellman** [comment]
@aruneko @dkastl I added master version. It's easy task.

**Comment by cayetanobv** [comment]
@smellman @smellman @dkastl we can follow the same convention as in main pgrouting repository, but you need to take account that only master merges are autodeployed at DockerHub. Anyway, we can re-think again the process to deploy Docker images at DockerHub.
Actually all autodeploys are failing now with folders rename
image

https://hub.docker.com/repository/docker/pgrouting/pgrouting/builds

**Comment by smellman** [comment]
@cayetanobv @dkastl Can you invite me to DockerHub? I want to check build configuration. My docker account is `smellman`.

**Comment by cayetanobv** [comment]
@dkastl I can't set permissions to @smellman . Could you do it?

**Comment by dkastl** [comment]
@smellman , I added your account.

@cayetanobv , that's a bit surprising that you couldn't do this, because I (probably) created a group "Owner" that everyone belongs to, and it should have full control over that organization.

**Comment by dkastl** [comment]
Screenshot from 2020-02-27 21-17-03

**Comment by cayetanobv** [comment]
> @smellman , I added your account.
> 
> @cayetanobv , that's a bit surprising that you couldn't do this, because I (probably) created a group "Owner" that everyone belongs to, and it should have full control over that organization.

Sorry @dkastl , you are right, I can handle permissions. I didn't look at the correct place at DockerHub.

**Comment by smellman** [comment]
@cayetanobv @dkastl @aruneko I fixes DockerHub settings. If it merged, DockerHub will make new build.

**Comment by cayetanobv** [comment]
Ok @smellman . I will merge

**Comment by smellman** [comment]
Thanks!

**Pull request merged**
