### PR TITLE
Update and rename README.md to README.☆

### PR DESCRIPTION
**Pull request by hashim361**
Fixes # .

Changes proposed in this pull request:
-
-
-

@pgRouting/admins

### CODE REVIEW

**Comment by hugovk** [comment]
@hashim361  Please don't create lots of spam PRs for Hacktoberfest, it's against the rules and values, and not fair on maintainers.

https://hacktoberfest.digitalocean.com/details#spam

Maintainers: please label this `invalid` so it's not counted towards Hacktoberfest.

image

**Review by dkastl — CHANGES_REQUESTED** [review]
Hacktoberfest spam ... this PR should be closed.

**Comment by cayetanobv** [comment]
thanks @dkastl @hugovk

**Comment by cayetanobv** [comment]
BTW: I've blocked this user form my repos
image

**Comment by hugovk** [comment]
I've been blocking and reporting blatant spammers, I got this reply for one (I think this sort of thing probably is against the GH ToS/AUP):

> Thanks for taking time to reach out. We're happy to take a look at the account and its activity. If we discover that GitHub's Terms of Service are being violated, we will take appropriate action.
>
> The content and activity you are reporting appears to be related to Hacktoberfest. Please keep in mind that GitHub Staff is not enforcing Hacktoberfest rules; we will, however, enforce our own Acceptable Use Policies. According to the Hacktoberfest FAQ:
>
> > We dislike seeing spam pull requests just as much as you, so please give them an invalid label and close them. Pull requests with an invalid label won’t be counted toward Hacktoberfest.
>
> Maintainers can also review this year's updated guidelines on reducing spam:
>
> https://hacktoberfest.digitalocean.com/details#spam
>
> Please let us know if we can help in any other way.

For repos that get multiple in a day, it's probably worth enabling the 24h "Limit to existing users" interaction limits (or some others too):

* https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/limiting-interactions-in-your-organization

**Comment by cayetanobv** [comment]
thanks for share this info @hugovk

**Comment by dkastl** [comment]
Thank you @hugovk . Highly appreciated!
Unfortunately by having these discussion spammers already are stealing our time.

However, I would prefer not to make it more difficult for contributors to interact with our projects. 
I think the first important thing is, that we can identify these pull requests, and I'm confident to be able to, because they are not very smart and their code changes are easy to be found as useless.

In the future someone might even come up with a Github bot to rate pull requests by quality and filter out garbage, maybe there is already one, I didn't search.

I think another idea is to keep spammers busy, that they can not steal their time in other projects.
So instead of declining a pull request, we could make a review and request a change. Some standard text we can easily copy and paste, a matter of seconds ;-)
When a pull request requires changes, it cannot be merged ... and after Hacktoberfest is over, we can cleanup.

**Pull request closed without merging**
