### PR TITLE
Correct the website url.  Should be pgrouting.org not pgrouting.net

### PR DESCRIPTION
**Pull request by robe2**
Fixes # .

Changes proposed in this pull request:
- change pgrouting.net  to pgrouting.org.  pgrouting.net does not exist.  pgrouting project site is pgrouting.org.
-
-

@pgRouting/admins

### CODE REVIEW

**Review by cayetanobv — APPROVED** [review]
thanks

**Comment by sanak** [comment]
Hi @cayetanobv, (CC: @robe2, @cvvergara)
I think that this is obvious fix, so merging this to `master` branch is helpful.
(Unless that, my working PR:#55 branch may conflict later.)

**Comment by cayetanobv** [comment]
Hi @sanak , that's true, you will have conflicts for sure with your branch. We have two alternatives:
- We can merge this PR and you need to fix later the conflicts in your branch.
- We can close this PR and you need to add these changes in your branch directly.

What do you think?

**Comment by sanak** [comment]
Hi @cayetanobv,
Thanks for confirmation.

> We can merge this PR and you need to fix later the conflicts in your branch.

I prefer this way.
After this PR is merged, then I will rebase PR:#55 branch.

**Comment by cayetanobv** [comment]
Ok, I'm going to merge this PR, and after that, you can start dealing with these changes in your PR.
Thanks for your work @sanak

**Comment by sanak** [comment]
Okay, thanks, too!

**Pull request merged**
