### PR TITLE
Added pgRouting v3.1.1 

### PR DESCRIPTION
**Pull request by cayetanobv**
Changes proposed in this pull request:
- Added pgRouting v3.1.1 
- upgraded master and dev versions

@pgRouting/admins

### CODE REVIEW

**Review by smellman — APPROVED** [review]
Is is OK but it needs test after my [PR](https://github.com/postgis/docker-postgis/pull/211).

**Comment by cayetanobv** [comment]
> Is is OK but it needs test after my [PR](https://github.com/postgis/docker-postgis/pull/211).

Ok, we will wait :) thanks @smellman

**Review by aruneko — APPROVED** [review]

**Review by dkastl — APPROVED** [review]
Very fast. Thank you!

**Review by sanak — APPROVED** [review]

**Review by cvvergara — APPROVED** [review]
I am blindly approving.
I really tried to understand what is going on, with no success
I trust you all.

**Comment by cayetanobv** [comment]
@smellman Can we merge? Did you test it after PostGIS repo PR merge?

**Comment by smellman** [comment]
@cayetanobv docker-posgis merged new PR and CI create new docker images now.
https://travis-ci.org/github/postgis/docker-postgis/builds/745779442
After this process, we can merge this PR.

**Pull request merged**
